apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
spec:
  instances: {{.Values.keyCloakCluster.instances}}
  externalAccess:
    enabled: {{.Values.keyCloakCluster.externalAccess}}